"""add cost_tier to prompt_templates

Revision ID: 0958ea246d40
Revises: 006
Create Date: 2026-09-15 11:19:50.987067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0958ea246d40'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_embeddings_entity', table_name='document_embeddings')
    op.drop_index('ix_document_embeddings_project_type', table_name='document_embeddings')
    op.drop_table('document_embeddings')
    op.alter_column('chapter_outlines', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('chapter_outlines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chapter_outlines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_chapter_outlines_outline', table_name='chapter_outlines')
    op.drop_index('idx_chapter_outlines_outline_number', table_name='chapter_outlines')
    op.create_index(op.f('ix_chapter_outlines_outline_id'), 'chapter_outlines', ['outline_id'], unique=False)
    op.alter_column('chapter_versions', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chapter_versions', 'token_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chapter_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_chapter_versions_chapter', table_name='chapter_versions')
    op.drop_index('idx_chapter_versions_chapter_created', table_name='chapter_versions')
    op.drop_index('idx_chapter_versions_chapter_type_created', table_name='chapter_versions')
    op.create_index(op.f('ix_chapter_versions_change_type'), 'chapter_versions', ['change_type'], unique=False)
    op.create_index(op.f('ix_chapter_versions_created_at'), 'chapter_versions', ['created_at'], unique=False)
    op.alter_column('chapters', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'token_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('chapters', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'empty'::character varying"))
    op.alter_column('chapters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chapters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_chapters_content_trgm', table_name='chapters', postgresql_using='gin')
    op.drop_index('idx_chapters_generation_status', table_name='chapters')
    op.drop_index('idx_chapters_outline', table_name='chapters')
    op.drop_index('idx_chapters_outline_updated', table_name='chapters')
    op.drop_index('idx_chapters_status', table_name='chapters')
    op.create_index(op.f('ix_chapters_chapter_outline_id'), 'chapters', ['chapter_outline_id'], unique=False)
    op.create_index(op.f('ix_chapters_generation_status'), 'chapters', ['generation_status'], unique=False)
    op.create_index(op.f('ix_chapters_status'), 'chapters', ['status'], unique=False)
    op.alter_column('character_appearances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_relations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'token_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_chat_messages_project_created', table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_created_at'), 'chat_messages', ['created_at'], unique=False)
    op.alter_column('cost_budgets', 'current_usage',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('cost_budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cost_budgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cover_images', 'is_selected',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('cover_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('foreshadowings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('foreshadowings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_foreshadowings_plant_chapter', table_name='foreshadowings')
    op.drop_index('idx_foreshadowings_project_status', table_name='foreshadowings')
    op.drop_index('idx_foreshadowings_resolution_chapter', table_name='foreshadowings')
    op.create_index(op.f('ix_foreshadowings_plant_chapter_id'), 'foreshadowings', ['plant_chapter_id'], unique=False)
    op.create_index(op.f('ix_foreshadowings_resolution_chapter_id'), 'foreshadowings', ['resolution_chapter_id'], unique=False)
    op.create_index(op.f('ix_foreshadowings_status'), 'foreshadowings', ['status'], unique=False)
    op.alter_column('generation_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.alter_column('generation_logs', 'token_input',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('generation_logs', 'token_output',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('generation_logs', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('generation_logs', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('generation_logs', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('generation_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_generation_logs_chapter', table_name='generation_logs')
    op.drop_index('idx_generation_logs_created', table_name='generation_logs')
    op.alter_column('model_configs', 'input_cost_per_1k',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('model_configs', 'output_cost_per_1k',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('model_configs', 'max_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('4096'))
    op.alter_column('model_configs', 'max_context_tokens',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('8192'))
    op.alter_column('model_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('model_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('outlines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('outlines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_project_notes_project', table_name='project_notes')
    op.create_index(op.f('ix_project_notes_project_id'), 'project_notes', ['project_id'], unique=False)
    op.alter_column('projects', 'language',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'zh-CN'::character varying"))
    op.alter_column('projects', 'target_words_per_chapter_min',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('3000'))
    op.alter_column('projects', 'target_words_per_chapter_max',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('5000'))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('projects', 'dialogue_ratio',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=False,
               existing_server_default=sa.text('0.40'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_projects_status', table_name='projects')
    # Add cost_tier column as nullable first (to handle existing data)
    op.add_column('prompt_templates', sa.Column('cost_tier', sa.String(length=20), nullable=True))
    # Backfill existing rows with default value
    op.execute("UPDATE prompt_templates SET cost_tier = 'standard' WHERE cost_tier IS NULL")
    # Now make it NOT NULL
    op.alter_column('prompt_templates', 'cost_tier', nullable=False)
    op.alter_column('prompt_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('scenes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_scenes_chapter', table_name='scenes')
    op.create_index(op.f('ix_scenes_chapter_id'), 'scenes', ['chapter_id'], unique=False)
    op.alter_column('story_bible', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('story_bible', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_story_bible_project', table_name='story_bible')
    op.create_index(op.f('ix_story_bible_project_id'), 'story_bible', ['project_id'], unique=False)
    op.alter_column('story_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('terminologies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('terminologies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index('idx_terminologies_project', table_name='terminologies')
    op.create_index(op.f('ix_terminologies_project_id'), 'terminologies', ['project_id'], unique=False)
    op.create_index(op.f('ix_terminologies_term'), 'terminologies', ['term'], unique=False)
    op.alter_column('worldviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('worldviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('writing_goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('writing_goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('writing_goals', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('writing_goals', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('worldviews', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('worldviews', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_terminologies_term'), table_name='terminologies')
    op.drop_index(op.f('ix_terminologies_project_id'), table_name='terminologies')
    op.create_index('idx_terminologies_project', 'terminologies', ['project_id'], unique=False)
    op.alter_column('terminologies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('terminologies', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('story_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_story_bible_project_id'), table_name='story_bible')
    op.create_index('idx_story_bible_project', 'story_bible', ['project_id'], unique=False)
    op.alter_column('story_bible', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('story_bible', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_scenes_chapter_id'), table_name='scenes')
    op.create_index('idx_scenes_chapter', 'scenes', ['chapter_id'], unique=False)
    op.alter_column('scenes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('scenes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('prompt_templates', 'is_default',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('prompt_templates', 'cost_tier')
    op.create_index('idx_projects_status', 'projects', ['status'], unique=False)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('projects', 'dialogue_ratio',
               existing_type=sa.NUMERIC(precision=3, scale=2),
               nullable=True,
               existing_server_default=sa.text('0.40'))
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'draft'::character varying"))
    op.alter_column('projects', 'target_words_per_chapter_max',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('5000'))
    op.alter_column('projects', 'target_words_per_chapter_min',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('3000'))
    op.alter_column('projects', 'language',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'zh-CN'::character varying"))
    op.drop_index(op.f('ix_project_notes_project_id'), table_name='project_notes')
    op.create_index('idx_project_notes_project', 'project_notes', ['project_id'], unique=False)
    op.alter_column('project_notes', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('project_notes', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('outlines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('outlines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('model_configs', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('model_configs', 'max_context_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('8192'))
    op.alter_column('model_configs', 'max_tokens',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('4096'))
    op.alter_column('model_configs', 'output_cost_per_1k',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('model_configs', 'input_cost_per_1k',
               existing_type=sa.NUMERIC(precision=10, scale=6),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.create_index('idx_generation_logs_created', 'generation_logs', ['created_at'], unique=False)
    op.create_index('idx_generation_logs_chapter', 'generation_logs', ['chapter_id'], unique=False)
    op.alter_column('generation_logs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_logs', 'retry_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('generation_logs', 'duration_ms',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('generation_logs', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('generation_logs', 'token_output',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('generation_logs', 'token_input',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('generation_logs', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_index(op.f('ix_foreshadowings_status'), table_name='foreshadowings')
    op.drop_index(op.f('ix_foreshadowings_resolution_chapter_id'), table_name='foreshadowings')
    op.drop_index(op.f('ix_foreshadowings_plant_chapter_id'), table_name='foreshadowings')
    op.create_index('idx_foreshadowings_resolution_chapter', 'foreshadowings', ['resolution_chapter_id'], unique=False)
    op.create_index('idx_foreshadowings_project_status', 'foreshadowings', ['project_id', 'status'], unique=False)
    op.create_index('idx_foreshadowings_plant_chapter', 'foreshadowings', ['plant_chapter_id'], unique=False)
    op.alter_column('foreshadowings', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('foreshadowings', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cover_images', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cover_images', 'is_selected',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('cost_budgets', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cost_budgets', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('cost_budgets', 'current_usage',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.drop_index(op.f('ix_chat_messages_created_at'), table_name='chat_messages')
    op.create_index('idx_chat_messages_project_created', 'chat_messages', ['project_id', 'created_at'], unique=False)
    op.alter_column('chat_messages', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chat_messages', 'token_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('characters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('characters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_relations', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('character_appearances', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_chapters_status'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_generation_status'), table_name='chapters')
    op.drop_index(op.f('ix_chapters_chapter_outline_id'), table_name='chapters')
    op.create_index('idx_chapters_status', 'chapters', ['status'], unique=False)
    op.create_index('idx_chapters_outline_updated', 'chapters', ['chapter_outline_id', 'updated_at'], unique=False)
    op.create_index('idx_chapters_outline', 'chapters', ['chapter_outline_id'], unique=False)
    op.create_index('idx_chapters_generation_status', 'chapters', ['generation_status'], unique=False)
    op.create_index('idx_chapters_content_trgm', 'chapters', ['content'], unique=False, postgresql_using='gin')
    op.alter_column('chapters', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chapters', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chapters', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'empty'::character varying"))
    op.alter_column('chapters', 'cost',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('chapters', 'token_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chapters', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_chapter_versions_created_at'), table_name='chapter_versions')
    op.drop_index(op.f('ix_chapter_versions_change_type'), table_name='chapter_versions')
    op.create_index('idx_chapter_versions_chapter_type_created', 'chapter_versions', ['chapter_id', 'change_type', 'created_at'], unique=False)
    op.create_index('idx_chapter_versions_chapter_created', 'chapter_versions', ['chapter_id', 'created_at'], unique=False)
    op.create_index('idx_chapter_versions_chapter', 'chapter_versions', ['chapter_id'], unique=False)
    op.alter_column('chapter_versions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chapter_versions', 'token_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('chapter_versions', 'word_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_chapter_outlines_outline_id'), table_name='chapter_outlines')
    op.create_index('idx_chapter_outlines_outline_number', 'chapter_outlines', ['outline_id', 'chapter_number'], unique=False)
    op.create_index('idx_chapter_outlines_outline', 'chapter_outlines', ['outline_id'], unique=False)
    op.alter_column('chapter_outlines', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chapter_outlines', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('chapter_outlines', 'status',
               existing_type=sa.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.create_table('document_embeddings',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('entity_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('entity_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('chunk_text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('chunk_index', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True),
    sa.Column('embedding', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('metadata_json', sa.TEXT(), server_default=sa.text("'{}'::text"), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='document_embeddings_project_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='document_embeddings_pkey')
    )
    op.create_index('ix_document_embeddings_project_type', 'document_embeddings', ['project_id', 'entity_type'], unique=False)
    op.create_index('ix_document_embeddings_entity', 'document_embeddings', ['entity_type', 'entity_id'], unique=False)
    # ### end Alembic commands ###
